

# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "The Charandeep Kapoor.com"
languageCode = "en-us"
baseURL = "https://charandeepkapoor.com/"
copyright = "Charandeep Kapoor© {2020}"

# Add your Disqus shortname here.
disqusShortname = "seo-with-charan"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-174140976-1" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Monday, January 2, 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/ck7_eth"
  github = "https://github.com/SirCharan"
  email = "mailto:charandeepkapoor3@gmail.com"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://www.instagram.com/not_the_niceguy/"
  linkedin = "https://www.linkedin.com/in/seo-with-charan"
  youtube = "https://www.youtube.com/@Charandeepkapoor"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Facebook", "LinkedIn", "YouTube", "Instagram", "Email"]

  # Metadata for Twitter cards, defaults to params.twitter
   twitterSite = "@ck7_eth"
  twitterAuthor = "@ck7_eth"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
